import { Injectable, Inject, ConflictException, BadRequestException } from '@nestjs/common';
import { type ProjectRepository } from '../../infrastracture/repositories/project.repository';
import { PROJECT_REPOSITORY } from '../../domain/constants/project.constants';
import { Project as ProjectEntity } from '../../domain/entities/project.entity';
import { CreateProjectDto } from '../api/dto/request/create-project-dto';
import { USER_REPOSITORY } from 'src/features/users/domain/constants/user.constants';
import { type UserRepository } from 'src/features/users/infrastracture/repositories/user.repository';
import { ProjectMemberRole } from '../../domain/enums/project-member-role.enum';

@Injectable()
export class CreateProjectUseCase {
  constructor(
    @Inject(PROJECT_REPOSITORY)
    private readonly projectRepository: ProjectRepository,
    @Inject(USER_REPOSITORY)
    private readonly userRepository: UserRepository,
  ) {}

  async execute(dto: CreateProjectDto): Promise<ProjectEntity> {
    const existingProject = await this.projectRepository.findByName(dto.name);
    
    // Convert to Date object and handle validation
    const finishDate = new Date(dto.finishDate);
    const now = new Date();

    if (existingProject) {
      throw new ConflictException(`Project with name ${dto.name} already exists`);
    }

    if (finishDate <= now) {
      throw new BadRequestException('Finish date must be in the future');
    }

    await this.validateMembers(dto.memberIds);

    const projectEntity = new ProjectEntity(
      '', // ID will be generated by DB
      dto.name,
      dto.status,
      dto.finishDate,
    );

    const createdProject = await this.projectRepository.create(projectEntity);

    if (dto.memberIds?.length) {
      await this.projectRepository.replaceMembers(
        createdProject.id,
        dto.memberIds,
        ProjectMemberRole.MEMBER,
      );
      const projectWithMembers = await this.projectRepository.findById(createdProject.id);
      if (projectWithMembers) {
        return projectWithMembers;
      }
    }

    return createdProject;
  }

  private async validateMembers(memberIds?: string[]): Promise<void> {
    if (!memberIds?.length) {
      return;
    }

    const users = await this.userRepository.findByIds(memberIds);
    const userMap = new Map(users.map((user) => [user.id, user]));

    for (const memberId of memberIds) {
      const user = userMap.get(memberId);
      if (!user) {
        throw new BadRequestException(`User with ID '${memberId}' does not exist`);
      }
      if (user.role === 'ADMIN') {
        throw new BadRequestException(
          `User '${user.name}' has role 'ADMIN' and cannot be added as a project member.`,
        );
      }
    }
  }
}
