import { Injectable, Inject, ConflictException, BadRequestException } from '@nestjs/common';
import { type ProjectRepository } from '../../../infrastracture/repositories/project.repository';
import { PROJECT_REPOSITORY } from '../../../domain/constants/project.constants';
import { Project as ProjectEntity } from '../../../domain/entities/project.entity';
import { CreateProjectDto } from '../dto/request/create-project-dto';

@Injectable()
export class CreateProjectUseCase {
  constructor(
    @Inject(PROJECT_REPOSITORY)
    private readonly projectRepository: ProjectRepository,
  ) {}

  async execute(dto: CreateProjectDto): Promise<ProjectEntity> {
    const existingProject = await this.projectRepository.findByName(dto.name);
    
    // Convert to Date object and handle validation
    const finishDate = new Date(dto.finishDate);
    const now = new Date();

    if (existingProject) {
      throw new ConflictException(`Project with name ${dto.name} already exists`);
    }

    if (finishDate <= now) {
      throw new BadRequestException('Finish date must be in the future');
    }

    const projectEntity = new ProjectEntity(
      '', // ID will be generated by DB
      dto.name,
      dto.status,
      dto.finishDate,
    );
    
    return this.projectRepository.create(projectEntity);
  }
}
