import { Injectable, Inject, NotFoundException, BadRequestException } from '@nestjs/common';
import { type TeamRepository } from '../../infrastracture/repository/team-repository';
import { TEAM_REPOSITORY } from '../../domain/constants/team.constants';
import { SPRINT_REPOSITORY } from '../../../sprints/domain/constants/sprint.constants';
import { PROJECT_REPOSITORY } from '../../../project/domain/constants/project.constants';
import { USER_REPOSITORY } from '../../../users/domain/constants/user.constants';
import { Team as TeamEntity } from '../../domain/entities/team.entity';
import { CreateTeamDto } from '../api/dto/request/create-team.dto';
import { type ProjectRepository } from '../../../project/infrastracture/repositories/project.repository';
import { type SprintRepository } from '../../../sprints/infrastracture/repository/sprint-repository';
import { type UserRepository } from '../../../users/infrastracture/repositories/user.repository';

@Injectable()
export class CreateTeamUseCase {
  constructor(
    @Inject(TEAM_REPOSITORY)
    private readonly teamRepository: TeamRepository,
    @Inject(SPRINT_REPOSITORY)
    private readonly sprintRepository: SprintRepository,
    @Inject(PROJECT_REPOSITORY)
    private readonly projectRepository: ProjectRepository,
    @Inject(USER_REPOSITORY)
    private readonly userRepository: UserRepository,
  ) { }

  async execute(dto: CreateTeamDto): Promise<TeamEntity> {

    const [sprint, existingTeams, existingUsers] = await Promise.all([
      this.sprintRepository.findById(dto.sprintId),
      this.teamRepository.findAll(dto.sprintId),
      this.userRepository.findByIds(dto.userIds.map(u => u.userId)),
    ]);

    if (!sprint) {
      throw new NotFoundException(`Sprint with ID ${dto.sprintId} not found`);
    }

    if (dto.projectId !== sprint.projectId) {
      throw new BadRequestException(
        `Project ID '${dto.projectId}' does not match the sprint's project '${sprint.projectId}'`
      );
    }

    // Fetch project using sprint's projectId (derives from sprint, no separate validation needed)
    const project = await this.projectRepository.findById(sprint.projectId);
    if (!project) {
      throw new NotFoundException(`Project with ID ${sprint.projectId} not found`);
    }

    // Validate that only one team can exist per sprinta
    if (existingTeams.length > 0) {
      throw new BadRequestException(
        `A team already exists for sprint '${sprint.name}'. Only one team is allowed per sprint.`
      );
    }

    // Validate that all users exist and their name/role match the database records
    const userMap = new Map(existingUsers.map(u => [u.id, u]));

    for (const userEntry of dto.userIds) {
      const dbUser = userMap.get(userEntry.userId);
      if (!dbUser) {
        throw new BadRequestException(`User with ID '${userEntry.userId}' does not exist`);
      }
      if (dbUser.role === 'ADMIN') {
        throw new BadRequestException(
          `User '${dbUser.name}' has role 'ADMIN' and cannot be added to a team. Only DEVS and QA roles are allowed.`
        );
      }
      if (dbUser.name !== userEntry.name) {
        throw new BadRequestException(
          `Name mismatch for user ID '${userEntry.userId}': expected '${dbUser.name}', got '${userEntry.name}'`
        );
      }
      if (dbUser.role !== userEntry.role) {
        throw new BadRequestException(
          `Role mismatch for user ID '${userEntry.userId}': expected '${dbUser.role}', got '${userEntry.role}'`
        );
      }
    }

    // Validate each user's leave date against the sprint's start and end date
    dto.userIds.forEach((user) => {
      if (user.leave && user.leave.length > 0) {
        user.leave.forEach((leave) => {
          const leaveDate = new Date(leave.leaveDate);
          const sprintStart = new Date(sprint.startDate);
          const sprintEnd = new Date(sprint.endDate);

          // Clear time for date-only comparison
          leaveDate.setHours(0, 0, 0, 0);
          sprintStart.setHours(0, 0, 0, 0);
          sprintEnd.setHours(0, 0, 0, 0);

          if (leaveDate < sprintStart || leaveDate > sprintEnd) {
            throw new BadRequestException(
              `Leave date '${leave.leaveDate.toISOString().split('T')[0]}' for user '${user.name}' is outside the sprint range (${sprint.startDate.toISOString().split('T')[0]} to ${sprint.endDate.toISOString().split('T')[0]})`
            );
          }
        });
      }
    });

    const teamEntity = new TeamEntity(
      '', // ID will be generated by DB
      project.id,
      project.name,
      project.status,
      sprint.id,
      sprint.name,
      sprint.status,
      dto.HoursDay,
      dto.userIds,
      dto.allocationPercentage,
      dto.calculatedHoursPerDay,
    );

    return this.teamRepository.create(teamEntity);
  }
}

