import { Injectable, Inject, ConflictException } from '@nestjs/common';
import { type UserRepository } from '../../infrastracture/repositories/user.repository';
import { USER_REPOSITORY } from '../../domain/constants/user.constants';
import { User as UserEntity } from '../../domain/entities/user.entity';
import { CreateUserDto } from 'src/features/users/application/api/dtos/request/create-user-dto';

@Injectable()
export class CreateUserUseCase {
  constructor(
    @Inject(USER_REPOSITORY)
    private readonly userRepository: UserRepository,
  ) { }

  async execute(dto: CreateUserDto): Promise<UserEntity> {
    const existingUser = await this.userRepository.findByEmail(dto.email);
    if (existingUser) {
      throw new ConflictException(`User with email already exists`);
    }

    const userEntity = new UserEntity(
      '', // ID will be generated by DB
      dto.name,
      dto.email,
      dto.role,
      dto.status
    );

    return this.userRepository.create(userEntity);
  }
}
