import { Injectable, Inject, ConflictException } from '@nestjs/common';
import { type SprintRepository } from '../../infrastracture/repository/sprint-repository';
import { Sprint as SprintEntity } from '../../domain/entities/sprint.entity';
import { CreateSprintDto } from '../api/dto/request/create-sprint-dto';

@Injectable()
export class CreateSprintUseCase {
  constructor(
    @Inject('SprintRepository')
    private readonly SprintRepository: SprintRepository,
  ) {}

  async execute(dto: CreateSprintDto): Promise<SprintEntity> {
    const existingSprint = await this.SprintRepository.findByName(dto.name);

    if (existingSprint) {
      throw new ConflictException(
        `Sprint with name ${dto.name} already exists`,
      );
    }

    const sprintEntity = new SprintEntity(
      '', // ID will be generated by DB
      dto.name,
      dto.status,
      dto.startDate,
      dto.endDate,
      dto.workingHoursDay,
    );

    return this.SprintRepository.create(sprintEntity);
  }
}
