import { Injectable, Inject, ConflictException, NotFoundException } from '@nestjs/common';
import { type SprintRepository } from '../../infrastracture/repository/sprint-repository';
import { Sprint as SprintEntity } from '../../domain/entities/sprint.entity';
import { CreateSprintDto } from '../api/dto/request/create-sprint-parent-dto';
import { type ProjectRepository } from '../../../project/infrastracture/repositories/project.repository';

@Injectable()
export class CreateSprintUseCase {
  constructor(
    @Inject('SprintRepository')
    private readonly SprintRepository: SprintRepository,
    @Inject('ProjectRepository')
    private readonly projectRepository: ProjectRepository,
  ) {}

  async execute(dto: CreateSprintDto): Promise<SprintEntity> {
    const project = await this.projectRepository.findById(dto.projectId);
    if (!project) {
      throw new NotFoundException(`Project with ID ${dto.projectId} not found`);
    }

    const existingSprint = await this.SprintRepository.findByName(dto.name);

    if (existingSprint) {
      throw new ConflictException(
        `Sprint with name ${dto.name} already exists`,
      );
    }

    const sprintEntity = new SprintEntity(
      '', // ID will be generated by DB
      dto.projectId,
      dto.name,
      dto.status,
      dto.startDate,
      dto.endDate,
      dto.workingHoursDay,
      dto.dayOff,
    );

    return this.SprintRepository.create(sprintEntity);
  }
}
