import { Injectable, Inject, ConflictException, NotFoundException, BadRequestException } from '@nestjs/common';
import { type SprintRepository } from '../../infrastracture/repository/sprint-repository';
import { SPRINT_REPOSITORY } from '../../domain/constants/sprint.constants';
import { PROJECT_REPOSITORY } from '../../../project/domain/constants/project.constants';
import { Sprint as SprintEntity } from '../../domain/entities/sprint-entity';
import { CreateSprintDto } from '../api/dto/request/create-sprint-parent-dto';
import { type ProjectRepository } from '../../../project/infrastracture/repositories/project.repository';
import { DateUtils } from '../../../../shared/date-utils';

@Injectable()
export class CreateSprintUseCase {
  constructor(
    @Inject(SPRINT_REPOSITORY)
    private readonly SprintRepository: SprintRepository,
    @Inject(PROJECT_REPOSITORY)
    private readonly projectRepository: ProjectRepository,
  ) { }

  async execute(dto: CreateSprintDto): Promise<SprintEntity> {
    const project = await this.projectRepository.findById(dto.projectId);

    // Normalize dates to start of day in UTC for strict calendar day comparison
    const start = new Date(dto.startDate);
    start.setUTCHours(0, 0, 0, 0);
    const end = new Date(dto.endDate);
    end.setUTCHours(0, 0, 0, 0);

    // Ensure end date is strictly after start date (different days)
    if (end.getTime() <= start.getTime()) {
      throw new BadRequestException('End date must be at least 1 day after the start date');
    }

    // Re-normalize end to end-of-day for range validation of day-offs
    const endRange = new Date(dto.endDate);
    endRange.setUTCHours(23, 59, 59, 999);

    if (dto.dayOff && dto.dayOff.length > 0) {
      for (const off of dto.dayOff) {
        const offDate = new Date(off.date);
        offDate.setUTCHours(0, 0, 0, 0);

        // Check if the day off is outside the range
        if (offDate.getTime() < start.getTime() || offDate.getTime() > endRange.getTime()) {
          throw new BadRequestException(
            `Invalid Day Off: "${off.label}" (${off.date}) is outside the sprint range (${dto.startDate} to ${dto.endDate})`
          );
        }
      }
    }

    // Validate minimum working days after day-offs
    const calculatedDuration = DateUtils.calculateWorkingDays(dto.startDate, dto.endDate, dto.dayOff);
    if (calculatedDuration < 2) {
      throw new BadRequestException('Day off date is invalid');
    }

    if (!project) {
      throw new NotFoundException(`Project with ID ${dto.projectId} not found`);
    }

    const existingSprint = await this.SprintRepository.findByName(dto.name);

    if (existingSprint) {
      throw new ConflictException(
        `Sprint with name ${dto.name} already exists`,
      );
    }

    const sprintEntity = new SprintEntity(
      '', // ID will be generated by DB
      dto.projectId,
      dto.name,
      dto.status,
      new Date(dto.startDate),
      new Date(dto.endDate),
      dto.workingHoursDay,
      dto.sprintDuration,
      dto.dayOff,
      dto.officialStartDate ? new Date(dto.officialStartDate) : null,
      dto.officialEndDate ? new Date(dto.officialEndDate) : null,
    );

    return this.SprintRepository.create(sprintEntity);
  }
}
