import { Injectable, Inject, ConflictException } from '@nestjs/common';
import { TICKET_REPOSITORY } from '../../domain/constants/ticket.constants';
import { type TicketRepository } from '../../infrastracture/repositories/tickets-repository';
import { CreateTicketDto } from '../api/dto/request/create-ticket-dto';
import { Ticket as TicketEntity } from '../../domain/entities/ticket.entity';

@Injectable()
export class CreateTicketUseCase {
  constructor(
    @Inject(TICKET_REPOSITORY)
    private readonly ticketRepository: TicketRepository,
  ) {}

  async execute(dto: CreateTicketDto): Promise<TicketEntity> {
    const existingTicket = await this.ticketRepository.findTicketNumber(dto.ticketNumber);

    if (existingTicket) {
      throw new ConflictException(`Ticket with number ${dto.ticketNumber} already exists`);
    }
    
    const ticketEntity = new TicketEntity(
      '', // ID will be generated by DB
      dto.ticketNumber,
      dto.ticketTitle,
      dto.descriptionLink,
      dto.status,
      dto.developmentEstimation,
      dto.estimationTesting,
    );
    
    return this.ticketRepository.create(ticketEntity);
  }
}
